# Generated by Django 5.1.7 on 2025-03-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=300)),
                ('ano_publi', models.DateTimeField(auto_now_add=True)),
                ('informacoes_adc', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Postagem',
        ),
    ]
